server:
  port: 7779
cards:
  datasource:
    url: jdbc:mysql://localhost:3306/cadrs?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
#    password: kodilla_password
#    username: kodilla_user
    password: Kamil791919099
    username: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  allow-get-cards: true
