server:
  port: 7778
customer:
  datasource:
    url: jdbc:mysql://localhost:3306/customer?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
    password: kodilla_passwordd
    username: kodilla_userr
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  allow-get-customer: true
